### ISSUE TITLE
Raise if there is a shared named parameter for a route

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_router#1]
So you can't do 

```
/users/:user_id/foo
/users/:something_else/bar
```

Because the router can't figure out which one it's supposed to do.

**Comment by robacarp** [comment]
As stated, this shouldn't be a problem. The router should accept any number of possible tokens at that position and continue to filter the match set. The remainder of the URL (foo or bar) would then appropriately select the correct url.

**Comment by paulcsmith** [comment]
Just to make sure I understand, you're saying that with a tail-first approach this would work so it wouldn't have to raise an error?

**Comment by paulcsmith** [comment]
I guess either way though it should raise if you do:

```
/users/:user_id/foo
/users/:something_else/foo
```

Because the second one would never match

**Comment by robacarp** [comment]
Not quite. Tail first is only needed when a glob is detected, and is unrelated to this. A variable segment should _always_ match, but be basically ignored until the rest of the route matches. For example, I expect these routes to work, and to provide named parameters correctly:

```
/users/:id
/users/:parent_id/children
```

**Comment by paulcsmith** [comment]
Ah yes, that works right now, but I don't think the initial example does. So I guess that would still be the case. TBH though I haven't touched the router part of Lucky in awhile so I'd have to take a closer look  to be sure :P

**Comment by jwoertink** [comment]
Just ran in to this issue. I have a ton of routes, and it didn't cross my mind that two could conflict, but I had

```crystal
# Api::VideoReleases::Index
"/api/:site_id/video_releases"

# Api::NetworkReleases::Index
"/api/:program_id/video_releases"
```

I kept getting a 404 and didn't understand why. I found out from running `lucky routes`, and then seeing that I had 2 defined close. I've worked around my issue, but wanted to document this. It would help for sure to have a compile-time error showing the clashing routes.
