### ISSUE TITLE
Single Page App (SPA) Catch All Route

### ISSUE THREAD

**Issue by russ** [luckyframework/lucky_router#12]
I'm working on a SPA with Vue and I'm running into the issue of the app not having a catch all route. 

The issue is that the Vue code can handle the routes if you navigate to them from inside the app but if you try to link directly to a route inside the app an error gets thrown because the Lucky router is looking to handle it before it gets to Vue.

Rails gives us the `match "*path"` route option. It would be really handy to have that.

I have another issue here, #3, for Route Globbing. This is pretty related. I'm wondering the current Lucky Router should be replaced by something like https://github.com/luislavena/radix

**Comment by jwoertink** [comment]
I did take a stab at doing this and was even successful aside from the fact that my version was REALLY slow lol. @robacarp may have some insight on this as well..

**Comment by paulcsmith** [comment]
Maybe we have a fallback option or something. Something like “fallback do/end” in an action that acts as the catch all route. 

Originally lucky used Radix but it was very buggy. It had lots of issues with routes not matching. 

I’d be open to some other router if it is fast and reliable with the standard 7 CRUD routes. If it does route globing too that’d be cool. 

We could also extend Lucky to use route globing like @jwoertink said but we’d need to speed it up. maybe if you open a PR we could maybe help spot that performance issue?

**Comment by paulcsmith** [comment]
In the meantime you could catch the NotFoundError in Errors::Show and render the Vuejs index page. That might work as a stopgap situation

**Comment by robacarp** [comment]
fallback routing is a great idea! Route globbing isn't a trivial problem to implement, but a fallback route would be. And I think it makes more sense to define it that way, because a glob processor is going to have to manually gobble up each url segment before it's able to match.

**Comment by russ** [comment]
@paulcsmith Awesome! That fixes my case for now.

**Comment by paulcsmith** [comment]
To keep things nice and simple, I've added a new section to the guides here! https://github.com/luckyframework/website/pull/199. I'll close this for now.

This way we don't need new functionality in the short term. I think this is a good solution for now, and maybe we can revisit later if this doesn't work. How does that sound? I can reopen if it doesn't work
