### ISSUE TITLE
Raise if there is a shared named param with a route with the same length, postion and name of static parts

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_router#41]
https://github.com/luckyframework/lucky_router/issues/1#issuecomment-489768260

This should raise since there is no way for a human or computer to know which one of these it should match.

```crystal
# Api::VideoReleases::Index
"/api/:site_id/video_releases"

# Api::NetworkReleases::Index
"/api/:program_id/video_releases"
```

However these _should still work_ since it has different lenghts and/or different static part names

```crystal
"/api/:program_id" # Different length
"/api/:program_id/something_else" # Same length but different static part name
"/api/:program_id/:foo" # Has a named part so it will first look for static match, then named part
```

**Comment by matthewmcgarvey** [comment]
What about when the request method differs? We store payloads by request method so the code can definitely handle differing path variables as long as the request method is different, but should we?

Implementation-wise, it's going to be hard to do the check _while_ inserting because you'd have to check down path variable branches before making a new path variable fragment. I don't know the solution but it's something to think about.

**Comment by jwoertink** [comment]
To add to this, there's a spec in Lucky already to track this: https://github.com/luckyframework/lucky/pull/929

**Comment by paulcsmith** [comment]
Yeah should definitely allow them if they're on different request methods.

For checking on insert I imagine this would be a totally separate thing. For example I'd say we store a normalized version of the path somewhere and then raise immediately (not when booting just to make it easier to code and test)

For example

```crystal
class LuckyRouter
  # This would likely be a Hash String => [] of String, where the key is the request method
  # Not doing that here though for simplicity
  class_property paths = [] of String

  # Call this when adding a route to the matcher
  def add_path(path : String)
     # normalize string so named sections are all the same
     # "/users/:user_id/settings" => "/users/:named_section/settings"
     if paths.include?(normalized_path)
         raise "#{path} cannot be added because...etc."
     end
  end
end
```

This doesn't handle every case but shows the rough idea I had in mind
