### ISSUE TITLE
Add some Documentation

### ISSUE THREAD

**Issue by Jcambass** [luckyframework/lucky_router#6]
To make contribution easier we should add some inline code documentation.

- [ ] Fragment
- [x] MatchFinder
- [x] Match
- [x] Matcher
- [x] NoMatch
- [ ] PartProcessor
- [ ] Route

I'm working on a Pull Request for this and will update my work here. 

Is there anything special to consider for lucky documentation? Otherwise, I'm gonna use the crystal guidelines. Maybe related to https://github.com/luckyframework/lucky/issues/275 ?

**Comment by edwardloveall** [comment]
Hey @Jcambass I'm also writing some documentation. Thank you for pitching in! Is there a specific crystal guideline for documentation writing? If you have a link I'd love to see it. I've been trying to use lots of real-world examples and sample code.

When I write some documentation I try to link it back to https://github.com/luckyframework/lucky/issues/275 so check there to make sure to make sure we're not stepping on each other.

**Comment by Jcambass** [comment]
Hi @edwardloveall I'm currently more of less just documenting the basics (Parameters, method descriptions). I try to link to related code as often as possible in order to make the whole Architecture more clear. I'm using the [official crystal documentation guidelines](https://crystal-lang.org/docs/conventions/documenting_code.html). They're quite simple. Also I check frequently how the docs look generated.

Since I'm linking to other Classes often in order to keep the docs dry I haven't commited most changes because they would lack some important parts when not linked to the documentation of other classes.

I'm gonna try to commit my current progress as soon as possible. As You can see the core router parts such as Fragment, PartProcessor and Route aren't documented yet. Mostly because I didn't have enough time to take a close enough look at the code to give the documentation clear meaning in an abstract way.

**Comment by edwardloveall** [comment]
Fantastic! Thanks for this and for the work you've done so far. Can't wait to read it!

**Comment by matthewmcgarvey** [comment]
I'm going to close this since it is quite stale. The inline documentation has evolved as the code has changed. Please make a new issue if you'd still like to do this 👍
